blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls'))
]

posts/urls.py
from django.urls import path
from posts.views import (
        home,
        post_detail,
        post_reply
    )


app_name = 'posts'

urlpatterns = [
    path('', home, name='home'),
    path('post/detail/<int:pk>', post_detail, name='post-detail'),
    path('post/reply/<int:pk>', post_reply, name='post-reply')
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

class PostReply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    content = models.TextField()

    class Meta:
        verbose_name_plural = 'Post replies'

    def __str__(self):
        return f'{self.user}'

posts/forms.py
from posts.models import PostReply
from django import forms


class PostReplyForm(forms.ModelForm):
    class Meta:
        model = PostReply
        fields = ['content']

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from posts.models import Post, PostReply
from posts.forms import PostReplyForm


def home(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'posts/home.html', context)


def post_detail(request, pk):
    try:
        post = get_object_or_404(Post, pk=pk)
        replies = post.postreply_set.all()
        print(replies)
        context = {
            'replies': replies,
            'post': post
        }
        return render(request, 'posts/post_detail.html', context)
    except:
        return redirect('posts:home')
    

def post_reply(request, pk):
    user = request.user
    replied_to = Post.objects.get(pk=pk)
    if request.method == 'POST':
        form = PostReplyForm(request.POST)
        if form.is_valid():
            data = form.save()
            reply = PostReply.objects.get(pk=data.pk)
            reply.user = user
            reply.post = replied_to
            reply.save()
        return redirect('posts:post-detail', pk=replied_to.pk)
    else:
        form = PostReplyForm()
        context = {
            'replied_to': replied_to,
            'form': form
        }
        return render(request, 'posts/post_reply.html', context)

posts/templates/posts/home.html
{% extends 'posts/index.html' %}


<title>
    {% block title %}
        Home
    {% endblock title %}
</title>


{% block content %}
    {% if message %}
        <p>{{ message }}</p>
    {% endif %}
    <div class="home-container">
        <h1 class="h1-header">Latest Posts</h1>
        <div class="posts-container">
            {% for post in posts %}
                <div class="post-wrapper">
                    <h3 class="title">{{ post.title }}</h3>
                    <p class="content">{{ post.content|truncatewords:50 }}</p>
                    <p class="author">{{ post.author.username }}</p>
                    <p class="date-created">{{ post.date_created }}</p>
                    <a href="{% url 'posts:post-detail' post.pk %}" class="see-detail-btn">Read more</a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

posts/templates/posts/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" 
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" 
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" type='text/css' href="{% static 'posts/style.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <header>
        <div class="nav-container">
            <div class="brand-container">
                <img src="{% static 'posts/images/brand-logo.png' %}" alt="">
                <a href="{% url 'posts:home' %}" class="brand">DjangoBlog</a>
            </div>
            <nav class="nav-items-wrapper">
                <ul class="nav-items">
                    <li class='solid-xmark-container'>
                        <!-- close -->
                        <i id='solid-xmark' class="fa-solid fa-xmark"></i>
                    </li>
                    {% if not request.user.is_authenticated %}
                        <li><a class='nav-item' href="{% url 'posts:home' %}">Home</a></li>
                        <li><a class='nav-item' href="">Communities</a></li>
                        <li><a class='nav-item' href="">About</a></li>
                        <li><a class='nav-item' href="">Contact</a></li>
                        <li><a class='nav-item' href="">Register</a></li>
                        <li><a class='nav-item' href="">Login</a></li>
                    {% else %}
                        <li><a class='nav-item' href="{% url 'posts:home' %}">Home</a></li>
                        <li><a class='nav-item' href="">Communities</a></li>
                        <li><a class='nav-item' href="">Create post</a></li>
                        <li><a class='nav-item' href="">About</a></li>
                        <li><a class='nav-item' href="">Contact</a></li>
                        <li><a class='nav-item' href="">Logout</a></li>
                    {% endif %}
                    
                </ul>
            </nav>
            <div class="nav-buttons">
                <i id='solid-bar' class="fa-solid fa-bars"></i>
            </div>
        </div>
        <div class="banner-img">
            <img src="{% static 'posts/images/banner.png' %}">
        </div>
    </header>
    <main>
        <div class="content-container">
            {% block content %}
            {% endblock content %}
        </div>
    </main>
    <footer>

    </footer>
    <script type="text/javascript">
        const bar = document.querySelector('#solid-bar')
        const xmark = document.querySelector('#solid-xmark')
        const body = document.querySelector('body')
        const navItemsWrapper = document.querySelector('.nav-items-wrapper')
        const navItems = document.querySelectorAll('.nav-item')

        for(i = 0; i < navItems.length; i++){
            let item = navItems[i]
            item.addEventListener('click', function(event){
                if(window.innerWidth < 1000) {
                    event.currentTarget.style.background = 'rgb(0, 128, 0)'
                }
                else if(window.innerWidth >=1000) {
                    event.currentTarget.style.backgroundColor = 'transparent'
                }
            })
        }

        window.addEventListener('resize', function(){
            if(window.innerWidth >= 1000 || window.innerWidth <= 1000){
                navItemsWrapper.classList.remove('show-nav-items-wrapper')
            }
        })
        
        window.addEventListener('scroll', function(){
            navItemsWrapper.classList.remove('show-nav-items-wrapper')
        })

        bar.addEventListener('click', function(){
            navItemsWrapper.classList.add('show-nav-items-wrapper')
        })

        xmark.addEventListener('click', function(){
            navItemsWrapper.classList.remove('show-nav-items-wrapper')
        })
    </script>
</body>
</html>

posts/templates/posts/post_detail.html
{% extends 'posts/index.html' %}

<title>
    {% block title %}
        Post detail
    {% endblock title %}
</title>

{% block content %}
    <div class="post-detail-container">
        <h1>
            post detail
        </h1>
        <div class="post-detail-wrapper">
            <h3 class="title">{{ post.title }}</h3>
            <p class="content">{{ post.content }}</p>
            <p class="author">{{ post.author.username }}</p>
            <p class="date-created">{{ post.date_created }}</p>
            <a href="{% url 'posts:post-reply' post.pk %}" class="reply-btn">Reply</a>
        </div>
        <br>
        <div class="post-reply-container">
            {% if replies %}
                {% for reply in replies %}
                    <div class="post-reply-wrapper" style="background: rgb(0, 161, 100); padding: 1rem; color: white; 
                    border-radius: 10px;">
                        <h3>Re: {{ post.title }}</h3>
                        <p>{{ reply.user.username }}</p>
                        <p>{{ reply.content }}</p>
                        <a href="" style="color: rgb(255, 0, 0)">Reply</a>
                    </div>
                    <br>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

posts/templates/posts/post_reply.html
{% extends 'posts/index.html' %}


<title>
    {% block title %}
        Reply-{{ replied_to }}
    {% endblock title %}
</title>

{% block content %}
    <div class="post-replied-container">
        <div class='post-replied-wrapper'>
            <h3 class="post-replied-title">{{ replied_to.title }}</h3>
            <p class="post-replied-content">{{ replied_to.content }}</p>
            <p>{{ replied_to.author }}</p>
            <p>{{ replied_to.date_created }}</p>
        </div>
        <form action="" method="POST">
            {% csrf_token %}
            <div>
                {{ form }}
            </div>
            <button>Reply</button>
        </form>
    </div>
{% endblock content %}